from tkinter import *
from tkinter import ttk
import tkinter.messagebox #popup messages
import random
import os
#GPA Optimizer Code
#Default (Main) Window {Optimizer}


window2= Tk()
window2.geometry("1366x768") #Dimensions of Application Window
window2.resizable(width=False, height=False) #Lock Size of window and disable maximize button
window2.title('OptiGrade 1.0') #Header/Title of Window

def M_quote():
    lst=['Where there is a will, there is a way. -Pauline Kael', 'If you can dream it, you can do it. -Walt Disney', 'Yes We Can! -Barrack Obama', 'Do not stop, do not linger in your journey, but strive for the mark set before you. -George Whitefield', 'The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt', 'Aim for the moon. If you miss, you may hit a star. -W. Clement Stone']
    tkinter.messagebox.showinfo('We believe in you!', random.choice(lst))

def A_quote():
    lst=['Meow Meow Meow', 'Quack Quack', 'Bhow Bhow Bhow', 'Neigggggggh', 'Rooooooooooar', 'Buck Buck Buckaaaaawk']
    tkinter.messagebox.showinfo("You need a hobby", random.choice(lst))

def credits():
    tkinter.messagebox.showinfo('Wow, people actually read this?','Software developed by: \n \n Ali Hamza \n Maaz Saeed \n Maham Shoaib \n \n (and Moazzam Moriani"s Typhoid)\n \n All Rights Reserved ® \n Thank You, for using GPA Otimizer 1.0')

def export():
    tkinter.messagebox.showinfo('Save Progress', "Input data has been exported and stored to file 'progress.txt', in the program's directory.")

def instructions():
    tkinter.messagebox.showinfo('Instructions', ' Step 1: Input all your marks for each course \n \n Step 2: Click "The Moment of Truth" \n \n Click "Save & Export Progress" to copy your marks to a .txt file')

def transferDSA():
    #Create empty lists for marks
    marks=[]
    Total_marks=[]

    #Append all obtained marks to list
    marks.append(quiz1.get())
    marks.append(quiz2.get())
    marks.append(quiz3.get())
    marks.append(quiz4.get())
    marks.append(quiz5.get())
    marks.append(quiz6.get())
    marks.append(quiz7.get())
    marks.append(lab1.get())
    marks.append(lab2.get())
    marks.append(lab3.get())
    marks.append(lab4.get())
    marks.append(lab5.get())
    marks.append(lab6.get())
    marks.append(lab7.get())
    marks.append(lab8.get())
    marks.append(ass1.get())
    marks.append(ass2.get())
    marks.append(ass3.get())
    marks.append(mid.get())
    marks.append(final.get())
    marks.append(proD.get())
    marks.append(proT.get())
    marks.append(proI.get())
    marks.append(proC.get())
    marks.append(proQ.get())
    marks.append(part.get())

    #Append all max marks to list
    Total_marks.append(quiz1_b.get())
    Total_marks.append(quiz2_b.get())
    Total_marks.append(quiz3_b.get())
    Total_marks.append(quiz4_b.get())
    Total_marks.append(quiz5_b.get())
    Total_marks.append(quiz6_b.get())
    Total_marks.append(quiz7_b.get())
    Total_marks.append(lab1_b.get())
    Total_marks.append(lab2_b.get())
    Total_marks.append(lab3_b.get())
    Total_marks.append(lab4_b.get())
    Total_marks.append(lab5_b.get())
    Total_marks.append(lab6_b.get())
    Total_marks.append(lab7_b.get())
    Total_marks.append(lab8_b.get())
    Total_marks.append(ass1_b.get())
    Total_marks.append(ass2_b.get())
    Total_marks.append(ass3_b.get())
    Total_marks.append(mid_b.get())
    Total_marks.append(final_b.get())
    Total_marks.append(proD_b.get())
    Total_marks.append(proT_b.get())
    Total_marks.append(proI_b.get())
    Total_marks.append(proC_b.get())
    Total_marks.append(proQ_b.get())
    Total_marks.append(part_b.get())
    print(marks)
    print(Total_marks)

def transferDM():
    #Create empty lists for marks
    marks=[]
    Total_marks=[]

    #Append all obtained marks to list
    marks.append(DMquiz1.get())
    marks.append(DMquiz2.get())
    marks.append(DMquiz3.get())
    marks.append(DMquiz4.get())
    marks.append(DMass1.get())
    marks.append(DMass2.get())
    marks.append(DMass3.get())
    marks.append(DMass4.get())
    marks.append(DMmid.get())
    marks.append(DMfinal.get())
    marks.append(DMpart.get())

    #Append all max marks to list
    Total_marks.append(DMquiz1_b.get())
    Total_marks.append(DMquiz2_b.get())
    Total_marks.append(DMquiz3_b.get())
    Total_marks.append(DMquiz4_b.get())
    Total_marks.append(DMass1_b.get())
    Total_marks.append(DMass2_b.get())
    Total_marks.append(DMass3_b.get())
    Total_marks.append(DMass4_b.get())
    Total_marks.append(DMmid_b.get())
    Total_marks.append(DMfinal_b.get())
    Total_marks.append(DMpart_b.get())
    print(marks)
    print(Total_marks)

def transferCAL():
    #Create empty lists for marks
    marks=[]
    Total_marks=[]

    #Append all obtained marks to list
    marks.append(CALquiz1.get())
    marks.append(CALquiz2.get())
    marks.append(CALquiz3.get())
    marks.append(CALtest1.get())
    marks.append(CALtest2.get())
    marks.append(CALtest3.get())
    marks.append(CALass1.get())
    marks.append(CALass2.get())
    marks.append(CALass3.get())
    marks.append(CALass4.get())
    marks.append(CALass5.get())
    marks.append(CALass6.get())
    marks.append(CALass7.get())
    marks.append(CALass8.get())
    marks.append(CALass9.get())
    marks.append(CALass10.get())
    marks.append(CALpro.get())
    marks.append(CALpeer.get())
    marks.append(CALfinal.get())

    #Append all max marks to list
    Total_marks.append(CALquiz1_b.get())
    Total_marks.append(CALquiz2_b.get())
    Total_marks.append(CALquiz3_b.get())
    Total_marks.append(CALtest1_b.get())
    Total_marks.append(CALtest2_b.get())
    Total_marks.append(CALtest3_b.get())
    Total_marks.append(CALass1_b.get())
    Total_marks.append(CALass2_b.get())
    Total_marks.append(CALass3_b.get())
    Total_marks.append(CALass4_b.get())
    Total_marks.append(CALass5_b.get())
    Total_marks.append(CALass6_b.get())
    Total_marks.append(CALass7_b.get())
    Total_marks.append(CALass8_b.get())
    Total_marks.append(CALass9_b.get())
    Total_marks.append(CALass10_b.get())
    Total_marks.append(CALpro_b.get())
    Total_marks.append(CALpeer_b.get())
    Total_marks.append(CALfinal_b.get())
    print(marks)
    print(Total_marks)

def transferMOD():
    #Create empty lists for marks
    marks=[]
    Total_marks=[]

    #Append all obtained marks to list
    marks.append(MODquiz1.get())
    marks.append(MODquiz2.get())
    marks.append(MODquiz3.get())
    marks.append(MODquiz4.get())
    marks.append(MODass1.get())
    marks.append(MODass2.get())
    marks.append(MODass3.get())
    marks.append(MODfinal.get())
    marks.append(MODpart.get())

    #Append all max marks to list
    Total_marks.append(MODquiz1_b.get())
    Total_marks.append(MODquiz2_b.get())
    Total_marks.append(MODquiz3_b.get())
    Total_marks.append(MODquiz4_b.get())
    Total_marks.append(MODass1_b.get())
    Total_marks.append(MODass2_b.get())
    Total_marks.append(MODass3_b.get())
    Total_marks.append(MODfinal_b.get())
    Total_marks.append(MODpart_b.get())
    print(marks)
    print(Total_marks)

def transferS():
    #Create empty lists for marks
    marks=[]
    Total_marks=[]

    #Append all obtained marks to list
    marks.append(Sass1.get())
    marks.append(Sass2.get())
    marks.append(Sass3.get())
    marks.append(Smid.get())
    marks.append(Sfinal.get())
    marks.append(Spart.get())

    #Append all max marks to list
    Total_marks.append(Sass1_b.get())
    Total_marks.append(Sass2_b.get())
    Total_marks.append(Sass3_b.get())
    Total_marks.append(Smid_b.get())
    Total_marks.append(Sfinal_b.get())
    Total_marks.append(Spart_b.get())
    print(marks)
    print(Total_marks)

#Buttons
button_one = Button(window2, text='How to use the Optimizer', bg='#196f5c', fg='white', command=instructions)
button_two = Button(window2, text="Motivational Quotes", bg="purple", fg='white', command=M_quote) #click button to call function
button_three = Button(window2, text='Random Animal Sayings', bg="#0569da", fg='white', command=A_quote)
button_four = Button(window2, text='This Button Does Nothing, Please stop clicking it', bg='green', fg='white')
button_five = Button(window2, text='Save & Export Progress', bg="#d92525", fg='white', command=export)
button_six = Button(window2, text='View Credits', bg="black", fg='white', command=credits)


button_one.grid(row=0, column=1) #Grid button onto window
button_two.grid(row=0, column=2)
button_three.grid(row=0, column=3)
button_four.grid(row=0, column=4)
button_five.grid(row=0, column=5)
button_six.grid(row=0, column=6)

#Creation of Tabular Area
rows=0
while rows < 50:
    window2.rowconfigure(rows, weight=1)
    window2.columnconfigure(rows, weight=1)
    rows +=1

tabs=ttk.Notebook(window2) #Creation: Tab Variable
tabs.grid(row=1, column=0, columnspan=50, rowspan=49, sticky='NESW') #Placement of Tab

page0 = ttk.Frame(tabs)
tabs.add(page0, text='Log-in')

page1 = ttk.Frame(tabs)
tabs.add(page1, text='Data Structures & Algorithms')

page2= ttk.Frame(tabs)
tabs.add(page2, text='Discrete Maths')

page3= ttk.Frame(tabs)
tabs.add(page3, text='Calculus II')

page4= ttk.Frame(tabs)
tabs.add(page4, text='What is Modernity?')

page5= ttk.Frame(tabs)
tabs.add(page5, text='Intro to Sustainability')

########################################################################################################################
#Tab 0 Code (Log-in)
canvas=Canvas(page0, width=1366, height=600)
canvas.grid(row=0,column=0)

pic=PhotoImage(file=os.getcwd()+'\\homebg.png')
canvas.create_image(0,0, image=pic, anchor=NW)

User=Label(page0, text='Please input your username')
userinput=Entry(page0, textvariable='username')
button_submit=Button(page0, text='Submit', bg='black', fg='white')
User.grid(row=1)
userinput.grid(row=2)
button_submit.grid(row=3)
########################################################################################################################
#Tab 1 Code (DSA)

#Input Variables
quiz1=IntVar()
quiz2=IntVar()
quiz3=IntVar()
quiz4=IntVar()
quiz5=IntVar()
quiz6=IntVar()
quiz7=IntVar()
quiz1_b=IntVar()
quiz2_b=IntVar()
quiz3_b=IntVar()
quiz4_b=IntVar()
quiz5_b=IntVar()
quiz6_b=IntVar()
quiz7_b=IntVar()

lab1=IntVar()
lab2=IntVar()
lab3=IntVar()
lab4=IntVar()
lab5=IntVar()
lab6=IntVar()
lab7=IntVar()
lab8=IntVar()
lab1_b=IntVar()
lab2_b=IntVar()
lab3_b=IntVar()
lab4_b=IntVar()
lab5_b=IntVar()
lab6_b=IntVar()
lab7_b=IntVar()
lab8_b=IntVar()

ass1=IntVar()
ass2=IntVar()
ass3=IntVar()
ass1_b=IntVar()
ass2_b=IntVar()
ass3_b=IntVar()

proD=IntVar()
proT=IntVar()
proI=IntVar()
proC=IntVar()
proQ=IntVar()
proD_b=IntVar()
proT_b=IntVar()
proI_b=IntVar()
proC_b=IntVar()
proQ_b=IntVar()

mid=IntVar()
mid_b=IntVar()
final=IntVar()
final_b=IntVar()

part=IntVar()
part_b=IntVar()

#Line Skipping Variables
empty1=Label(page1, text='                                                                                         ')
empty2=Label(page1, text='                                                                                         ')
empty3=Label(page1, text='                                                                                         ')
empty4=Label(page1, text='                                                                                         ')
empty5=Label(page1, text='                                                                                         ')
empty6=Label(page1, text='                                                                                         ')
empty7=Label(page1, text='                                                                                         ')
empty8=Label(page1, text='                                                                                         ')
empty9=Label(page1, text='                                                                                         ')
empty10=Label(page1, text='                                                                                        ')
empty11=Label(page1, text='                                                                                        ')
empty12=Label(page1, text='                                                                                        ')
empty13=Label(page1, text='                                                                                        ')
empty14=Label(page1, text='                                                                                        ')

empty1.grid(row=2, column=1)

#Input Header Text
header = Label(page1, text='Marks Obtained') #Create Text
header.grid(row=2, column=2) #Place Text onto Window
empty2.grid(row=2, column=3)
header_two=Label(page1, text='Maximum Marks')
header_two.grid(row=2, column=3)

#Text and Fields for Obtained Marks and Maximum Marks (User Input)
Field_one = Label(page1, text='Quiz 01') #Create Text
entry_one = Entry(page1, textvariable=quiz1) #Create Textfield
entry_one_b = Entry(page1, textvariable=quiz1_b)
Field_two = Label(page1, text='Quiz 02')
entry_two = Entry(page1, textvariable=quiz2)
entry_two_b = Entry(page1, textvariable=quiz2_b)
Field_three = Label(page1, text='Quiz 03')
entry_three = Entry(page1, textvariable=quiz3)
entry_three_b = Entry(page1, textvariable=quiz3_b)
Field_four = Label(page1, text='Quiz 04')
entry_four = Entry(page1, textvariable=quiz4)
entry_four_b = Entry(page1, textvariable=quiz4_b)
Field_five = Label(page1, text='Quiz 05')
entry_five = Entry(page1, textvariable=quiz5)
entry_five_b = Entry(page1, textvariable=quiz5_b)
Field_six = Label(page1, text='Quiz 06')
entry_six = Entry(page1, textvariable=quiz6)
entry_six_b = Entry(page1, textvariable=quiz6_b)
Field_seven = Label(page1, text='Quiz 07')
entry_seven = Entry(page1, textvariable=quiz7)
entry_seven_b = Entry(page1, textvariable=quiz7_b)
Field_eight = Label(page1, text='Lab 01')
entry_eight = Entry(page1, textvariable=lab1)
entry_eight_b = Entry(page1, textvariable=lab1_b)
Field_nine = Label(page1, text='Lab 02')
entry_nine = Entry(page1, textvariable=lab2)
entry_nine_b = Entry(page1, textvariable=lab2_b)
Field_ten = Label(page1, text='Lab 03')
entry_ten = Entry(page1, textvariable=lab3)
entry_ten_b = Entry(page1, textvariable=lab3_b)
Field_eleven = Label(page1, text='Lab 04')
entry_eleven = Entry(page1, textvariable=lab4)
entry_eleven_b = Entry(page1, textvariable=lab4_b)
Field_twelve = Label(page1, text='Lab 05')
entry_twelve = Entry(page1, textvariable=lab5)
entry_twelve_b = Entry(page1, textvariable=lab5_b)
Field_thirteen = Label(page1, text='Lab 06')
entry_thirteen = Entry(page1, textvariable=lab6)
entry_thirteen_b = Entry(page1, textvariable=lab6_b)
Field_fourteen = Label(page1, text='Lab 07')
entry_fourteen = Entry(page1, textvariable=lab7)
entry_fourteen_b = Entry(page1, textvariable=lab7_b)
Field_fifteen = Label(page1, text='Lab 08')
entry_fifteen = Entry(page1, textvariable=lab8)
entry_fifteen_b = Entry(page1, textvariable=lab8_b)
Field_sixteen = Label(page1, text='Assignment 01')
entry_sixteen = Entry(page1, textvariable=ass1)
entry_sixteen_b = Entry(page1, textvariable=ass1_b)
Field_seventeen = Label(page1, text='Assignment 02')
entry_seventeen = Entry(page1, textvariable=ass2)
entry_seventeen_b = Entry(page1, textvariable=ass2_b)
Field_eighteen = Label(page1, text='Assignment 03')
entry_eighteen = Entry(page1, textvariable=ass3)
entry_eighteen_b = Entry(page1, textvariable=ass3_b)
Field_nineteen = Label(page1, text='Mid-Term Exam')
entry_nineteen = Entry(page1, textvariable=mid)
entry_nineteen_b = Entry(page1, textvariable=mid_b)
Field_twenty = Label(page1, text='Final Exam')
entry_twenty = Entry(page1, textvariable=final)
entry_twenty_b = Entry(page1, textvariable=final_b)
Field_twentyone = Label(page1, text='Group Project Demo')
entry_twentyone = Entry(page1, textvariable=proD)
entry_twentyone_b = Entry(page1, textvariable=proD_b)
Field_twentytwo = Label(page1, text='Group Project Techniques')
entry_twentytwo = Entry(page1, textvariable=proT)
entry_twentytwo_b = Entry(page1, textvariable=proT_b)
Field_twentythree = Label(page1, text='Group Project Interface')
entry_twentythree = Entry(page1, textvariable=proI)
entry_twentythree_b = Entry(page1, textvariable=proI_b)
Field_twentyfour = Label(page1, text='Group Project Challenges')
entry_twentyfour = Entry(page1, textvariable=proC)
entry_twentyfour_b = Entry(page1, textvariable=proC_b)
Field_twentyfive = Label(page1, text='Group Project QnA')
entry_twentyfive = Entry(page1, textvariable=proQ)
entry_twentyfive_b = Entry(page1, textvariable=proQ_b)
Field_twentysix = Label(page1, text='Class Participation')
entry_twentysix = Entry(page1, textvariable=part)
entry_twentysix_b = Entry(page1, textvariable=part_b)


Field_one.grid(row=3, column=1) #Place Text onto window
entry_one.grid(row=3, column=2) #Place Textfield onto window
Field_two.grid(row=4, column=1)
entry_two.grid(row=4, column=2)
Field_three.grid(row=5, column=1)
entry_three.grid(row=5, column=2)
Field_four.grid(row=6, column=1)
entry_four.grid(row=6, column=2)
Field_five.grid(row=7, column=1)
entry_five.grid(row=7, column=2)
Field_six.grid(row=8, column=1)
entry_six.grid(row=8, column=2)
Field_seven.grid(row=9, column=1)
entry_seven.grid(row=9, column=2)
empty4.grid(row=10) #Skip Line
Field_eight.grid(row=11, column=1)
entry_eight.grid(row=11, column=2)
Field_nine.grid(row=12, column=1)
entry_nine.grid(row=12, column=2)
Field_ten.grid(row=13, column=1)
entry_ten.grid(row=13, column=2)
Field_eleven.grid(row=14, column=1)
entry_eleven.grid(row=14, column=2)
Field_twelve.grid(row=15, column=1)
entry_twelve.grid(row=15, column=2)
Field_thirteen.grid(row=16, column=1)
entry_thirteen.grid(row=16, column=2)
Field_fourteen.grid(row=17, column=1)
entry_fourteen.grid(row=17, column=2)
Field_fifteen.grid(row=18, column=1)
entry_fifteen.grid(row=18, column=2)
empty5.grid(row=19)
Field_sixteen.grid(row=20, column=1)
entry_sixteen.grid(row=20, column=2)
Field_seventeen.grid(row=21, column=1)
entry_seventeen.grid(row=21, column=2)
Field_eighteen.grid(row=22, column=1)
entry_eighteen.grid(row=22, column=2)
empty6.grid(row=23)
Field_nineteen.grid(row=24, column=1)
entry_nineteen.grid(row=24, column=2)
Field_twenty.grid(row=25, column=1)
entry_twenty.grid(row=25, column=2)
empty7.grid(row=26)
Field_twentyone.grid(row=27, column=1)
entry_twentyone.grid(row=27, column=2)
Field_twentytwo.grid(row=28, column=1)
entry_twentytwo.grid(row=28, column=2)
Field_twentythree.grid(row=29, column=1)
entry_twentythree.grid(row=29, column=2)
Field_twentyfour.grid(row=30, column=1)
entry_twentyfour.grid(row=30, column=2)
Field_twentyfive.grid(row=31, column=1)
entry_twentyfive.grid(row=31, column=2)
Field_twentysix.grid(row=33, column=1)
entry_twentysix.grid(row=33, column=2)

entry_one_b.grid(row=3, column=3)
entry_two_b.grid(row=4, column=3)
entry_three_b.grid(row=5, column=3)
entry_four_b.grid(row=6, column=3)
entry_five_b.grid(row=7, column=3)
entry_six_b.grid(row=8, column=3)
entry_seven_b.grid(row=9, column=3)
empty9.grid(row=10)
entry_eight_b.grid(row=11, column=3)
entry_nine_b.grid(row=12, column=3)
entry_ten_b.grid(row=13, column=3)
entry_eleven_b.grid(row=14, column=3)
entry_twelve_b.grid(row=15, column=3)
entry_thirteen_b.grid(row=16, column=3)
entry_fourteen_b.grid(row=17, column=3)
entry_fifteen_b.grid(row=18, column=3)
empty10.grid(row=19)
entry_sixteen_b.grid(row=20, column=3)
entry_seventeen_b.grid(row=21, column=3)
entry_eighteen_b.grid(row=22, column=3)
empty11.grid(row=23)
entry_nineteen_b.grid(row=24, column=3)
entry_twenty_b.grid(row=25, column=3)
empty12.grid(row=26)
entry_twentyone_b.grid(row=27, column=3)
entry_twentytwo_b.grid(row=28, column=3)
entry_twentythree_b.grid(row=29, column=3)
entry_twentyfour_b.grid(row=30, column=3)
entry_twentyfive_b.grid(row=31, column=3)
entry_twentysix_b.grid(row=33, column=3)

#Button
button_DSA = Button(page1, text='The Moment of Truth', bg='#f56108', fg='white', command=transferDSA)
button_DSA.grid()
########################################################################################################################
#Tab 2 Code (DM)

#Input Variables
DMquiz1=IntVar()
DMquiz2=IntVar()
DMquiz3=IntVar()
DMquiz4=IntVar()
DMquiz1_b=IntVar()
DMquiz2_b=IntVar()
DMquiz3_b=IntVar()
DMquiz4_b=IntVar()

DMass1=IntVar()
DMass2=IntVar()
DMass3=IntVar()
DMass4=IntVar()
DMass1_b=IntVar()
DMass2_b=IntVar()
DMass3_b=IntVar()
DMass4_b=IntVar()

DMmid=IntVar()
DMmid_b=IntVar()

DMfinal=IntVar()
DMfinal_b=IntVar()

DMpart=IntVar()
DMpart_b=IntVar()

#Line Skipping Variables
empty1=Label(page2, text='                                                                                         ')
empty2=Label(page2, text='                                                                                         ')
empty3=Label(page2, text='                                                                                         ')
empty4=Label(page2, text='                                                                                         ')
empty5=Label(page2, text='                                                                                         ')
empty6=Label(page2, text='                                                                                         ')
empty7=Label(page2, text='                                                                                         ')
empty8=Label(page2, text='                                                                                         ')

empty1.grid(row=2, column=1)

#Input Header Text
header = Label(page2, text='Marks Obtained') #Create Text
header.grid(row=2, column=2) #Place Text onto Window
empty2.grid(row=2, column=3)
header_two=Label(page2, text='Maximum Marks')
header_two.grid(row=2, column=3)

#Text and Fields for Obtained Marks and Maximum Marks (User Input)
Field_one = Label(page2, text='Quiz 01') #Create Text
entry_one = Entry(page2, textvariable=DMquiz1) #Create Textfield
entry_one_b = Entry(page2, textvariable=DMquiz1_b)
Field_two = Label(page2, text='Quiz 02')
entry_two = Entry(page2, textvariable=DMquiz2)
entry_two_b = Entry(page2, textvariable=DMquiz2_b)
Field_three = Label(page2, text='Quiz 03')
entry_three = Entry(page2, textvariable=DMquiz3)
entry_three_b = Entry(page2, textvariable=DMquiz3_b)
Field_four = Label(page2, text='Quiz 04')
entry_four= Entry(page2, textvariable=DMquiz4)
entry_four_b= Entry(page2, textvariable=DMquiz4_b)
Field_five = Label(page2, text='Assignment 01')
entry_five = Entry(page2, textvariable=DMass1)
entry_five_b = Entry(page2, textvariable=DMass1_b)
Field_six = Label(page2, text='Assignment 02')
entry_six = Entry(page2, textvariable=DMass2)
entry_six_b = Entry(page2, textvariable=DMass2_b)
Field_seven = Label(page2, text='Assignment 03')
entry_seven = Entry(page2, textvariable=DMass3)
entry_seven_b = Entry(page2, textvariable=DMass3_b)
Field_eight = Label(page2, text='Assignment 04')
entry_eight = Entry(page2, textvariable=DMass4)
entry_eight_b = Entry(page2, textvariable=DMass4_b)
Field_nine = Label(page2, text='Mid-Term Exam')
entry_nine = Entry(page2, textvariable=DMmid)
entry_nine_b = Entry(page2, textvariable=DMmid_b)
Field_ten = Label(page2, text='Final Exam')
entry_ten = Entry(page2, textvariable=DMfinal)
entry_ten_b = Entry(page2, textvariable=DMfinal_b)
Field_eleven = Label(page2, text='Class Participation')
entry_eleven = Entry(page2, textvariable=DMpart)
entry_eleven_b = Entry(page2, textvariable=DMpart_b)

Field_one.grid(row=3, column=1) #Place Text onto window
entry_one.grid(row=3, column=2) #Place Textfield onto window
Field_two.grid(row=4, column=1)
entry_two.grid(row=4, column=2)
Field_three.grid(row=5, column=1)
entry_three.grid(row=5, column=2)
Field_four.grid(row=6, column=1)
entry_four.grid(row=6, column=2)
empty3.grid(row=7)
Field_five.grid(row=8, column=1)
entry_five.grid(row=8, column=2)
Field_six.grid(row=9, column=1)
entry_six.grid(row=9, column=2)
Field_seven.grid(row=10, column=1)
entry_seven.grid(row=10, column=2)
Field_eight.grid(row=11, column=1)
entry_eight.grid(row=11, column=2)
empty4.grid(row=12, column=1)
Field_nine.grid(row=13, column=1)
entry_nine.grid(row=13, column=2)
Field_ten.grid(row=14, column=1)
entry_ten.grid(row=14, column=2)
empty5.grid(row=15)
Field_eleven.grid(row=16, column=1)
entry_eleven.grid(row=16, column=2)

entry_one_b.grid(row=3, column=3)
entry_two_b.grid(row=4, column=3)
entry_three_b.grid(row=5, column=3)
entry_four_b.grid(row=6, column=3)
empty6.grid(row=7)
entry_five_b.grid(row=8, column=3)
entry_six_b.grid(row=9, column=3)
entry_seven_b.grid(row=10, column=3)
entry_eight_b.grid(row=11, column=3)
empty7.grid(row=12)
entry_nine_b.grid(row=13, column=3)
entry_ten_b.grid(row=14, column=3)
empty8.grid(row=15)
entry_eleven_b.grid(row=16, column=3)

#Button
button_DM = Button(page2, text='The Moment of Truth', bg='#f56108', fg='white', command=transferDM)
button_DM.grid()
########################################################################################################################
#Tab 3 Code (Calculus II)

#Input Variables
CALquiz1=IntVar()
CALquiz2=IntVar()
CALquiz3=IntVar()
CALquiz1_b=IntVar()
CALquiz2_b=IntVar()
CALquiz3_b=IntVar()

CALtest1=IntVar()
CALtest2=IntVar()
CALtest3=IntVar()
CALtest1_b=IntVar()
CALtest2_b=IntVar()
CALtest3_b=IntVar()

CALass1=IntVar()
CALass2=IntVar()
CALass3=IntVar()
CALass4=IntVar()
CALass5=IntVar()
CALass6=IntVar()
CALass7=IntVar()
CALass8=IntVar()
CALass9=IntVar()
CALass10=IntVar()
CALass1_b=IntVar()
CALass2_b=IntVar()
CALass3_b=IntVar()
CALass4_b=IntVar()
CALass5_b=IntVar()
CALass6_b=IntVar()
CALass7_b=IntVar()
CALass8_b=IntVar()
CALass9_b=IntVar()
CALass10_b=IntVar()

CALpro=IntVar()
CALpro_b=IntVar()
CALpeer=IntVar()
CALpeer_b=IntVar()

CALfinal=IntVar()
CALfinal_b=IntVar()

#Line Skipping Variables
empty1=Label(page3, text='                                                                                         ')
empty2=Label(page3, text='                                                                                         ')
empty3=Label(page3, text='                                                                                         ')
empty4=Label(page3, text='                                                                                         ')
empty5=Label(page3, text='                                                                                         ')
empty6=Label(page3, text='                                                                                         ')
empty7=Label(page3, text='                                                                                         ')
empty8=Label(page3, text='                                                                                         ')
empty9=Label(page3, text='                                                                                         ')
empty10=Label(page3, text='                                                                                         ')

empty1.grid(row=2, column=1)

#Input Header Text
header = Label(page3, text='Marks Obtained') #Create Text
header.grid(row=2, column=2) #Place Text onto Window
empty2.grid(row=2, column=3)
header_two=Label(page3, text='Maximum Marks')
header_two.grid(row=2, column=3)

#Text and Fields for Obtained Marks and Maximum Marks (User Input)
Field_one = Label(page3, text='Quiz 01') #Create Text
entry_one = Entry(page3, textvariable=CALquiz1) #Create Textfield
entry_one_b = Entry(page3, textvariable=CALquiz1_b)
Field_two = Label(page3, text='Quiz 02')
entry_two = Entry(page3, textvariable=CALquiz2)
entry_two_b = Entry(page3, textvariable=CALquiz2_b)
Field_three = Label(page3, text='Quiz 03')
entry_three = Entry(page3, textvariable=CALquiz3)
entry_three_b = Entry(page3, textvariable=CALquiz3_b)
Field_four = Label(page3, text='Test 01')
entry_four = Entry(page3, textvariable=CALtest1)
entry_four_b = Entry(page3, textvariable=CALtest1_b)
Field_five = Label(page3, text='Test 02')
entry_five = Entry(page3, textvariable=CALtest2)
entry_five_b = Entry(page3, textvariable=CALtest2_b)
Field_six = Label(page3, text='Test 03')
entry_six = Entry(page3, textvariable=CALtest3)
entry_six_b = Entry(page3, textvariable=CALtest3_b)
Field_seven = Label(page3, text='Homework 01')
entry_seven= Entry(page3, textvariable=CALass1)
entry_seven_b= Entry(page3, textvariable=CALass1_b)
Field_eight = Label(page3, text='Homework 02')
entry_eight = Entry(page3, textvariable=CALass2)
entry_eight_b = Entry(page3, textvariable=CALass2_b)
Field_nine = Label(page3, text='Homework 03')
entry_nine = Entry(page3, textvariable=CALass3)
entry_nine_b = Entry(page3, textvariable=CALass3_b)
Field_ten = Label(page3, text='Homework 04')
entry_ten = Entry(page3, textvariable=CALass4)
entry_ten_b = Entry(page3, textvariable=CALass4_b)
Field_eleven = Label(page3, text='Homework 05')
entry_eleven = Entry(page3, textvariable=CALass5)
entry_eleven_b = Entry(page3, textvariable=CALass5_b)
Field_twelve = Label(page3, text='Homework 06')
entry_twelve = Entry(page3, textvariable=CALass6)
entry_twelve_b = Entry(page3, textvariable=CALass6_b)
Field_thirteen = Label(page3, text='Homework 07')
entry_thirteen = Entry(page3, textvariable=CALass7)
entry_thirteen_b = Entry(page3, textvariable=CALass7_b)
Field_fourteen = Label(page3, text='Homework 08')
entry_fourteen = Entry(page3, textvariable=CALass8)
entry_fourteen_b = Entry(page3, textvariable=CALass8_b)
Field_fifteen = Label(page3, text='Homework 09')
entry_fifteen = Entry(page3, textvariable=CALass9)
entry_fifteen_b = Entry(page3, textvariable=CALass9_b)
Field_sixteen = Label(page3, text='Homework 10')
entry_sixteen = Entry(page3, textvariable=CALass10)
entry_sixteen_b = Entry(page3, textvariable=CALass10_b)
Field_seventeen = Label(page3, text='Class Project')
entry_seventeen = Entry(page3, textvariable=CALpro)
entry_seventeen_b = Entry(page3, textvariable=CALpro_b)
Field_eighteen = Label(page3, text='Peer Review')
entry_eighteen = Entry(page3, textvariable=CALpeer)
entry_eighteen_b = Entry(page3, textvariable=CALpeer_b)
Field_nineteen = Label(page3, text='Final Exam')
entry_nineteen = Entry(page3, textvariable=CALfinal)
entry_nineteen_b = Entry(page3, textvariable=CALfinal_b)

Field_one.grid(row=3, column=1) #Place Text onto window
entry_one.grid(row=3, column=2) #Place Textfield onto window
Field_two.grid(row=4, column=1)
entry_two.grid(row=4, column=2)
Field_three.grid(row=5, column=1)
entry_three.grid(row=5, column=2)
empty3.grid(row=6)
Field_four.grid(row=7, column=1)
entry_four.grid(row=7, column=2)
Field_five.grid(row=8, column=1)
entry_five.grid(row=8, column=2)
Field_six.grid(row=9, column=1)
entry_six.grid(row=9, column=2)
empty4.grid(row=10)
Field_seven.grid(row=11, column=1)
entry_seven.grid(row=11, column=2)
Field_eight.grid(row=12, column=1)
entry_eight.grid(row=12, column=2)
Field_nine.grid(row=13, column=1)
entry_nine.grid(row=13, column=2)
Field_ten.grid(row=14, column=1)
entry_ten.grid(row=14, column=2)
Field_eleven.grid(row=15, column=1)
entry_eleven.grid(row=15, column=2)
Field_twelve.grid(row=16, column=1)
entry_twelve.grid(row=16, column=2)
Field_thirteen.grid(row=17, column=1)
entry_thirteen.grid(row=17, column=2)
Field_fourteen.grid(row=18, column=1)
entry_fourteen.grid(row=18, column=2)
Field_fifteen.grid(row=19, column=1)
entry_fifteen.grid(row=19, column=2)
Field_sixteen.grid(row=20, column=1)
entry_sixteen.grid(row=20, column=2)
empty5.grid(row=21)
Field_seventeen.grid(row=22, column=1)
entry_seventeen.grid(row=22, column=2)
Field_eighteen.grid(row=23, column=1)
entry_eighteen.grid(row=23, column=2)
empty6.grid(row=24)
Field_nineteen.grid(row=25, column=1)
entry_nineteen.grid(row=25, column=2)

entry_one_b.grid(row=3, column=3)
entry_two_b.grid(row=4, column=3)
entry_three_b.grid(row=5, column=3)
empty7.grid(row=6)
entry_four_b.grid(row=7, column=3)
entry_five_b.grid(row=8, column=3)
entry_six_b.grid(row=9, column=3)
empty8.grid(row=10)
entry_seven_b.grid(row=11, column=3)
entry_eight_b.grid(row=12, column=3)
entry_nine_b.grid(row=13, column=3)
entry_ten_b.grid(row=14, column=3)
entry_eleven_b.grid(row=15, column=3)
entry_twelve_b.grid(row=16, column=3)
entry_thirteen_b.grid(row=17, column=3)
entry_fourteen_b.grid(row=18, column=3)
entry_fifteen_b.grid(row=19, column=3)
entry_sixteen_b.grid(row=20, column=3)
empty9.grid(row=21)
entry_seventeen_b.grid(row=22, column=3)
entry_eighteen_b.grid(row=23, column=3)
empty10.grid(row=24)
entry_nineteen_b.grid(row=25, column=3)

#Button
button_calc = Button(page3, text='The Moment of Truth', bg='#f56108', fg='white', command=transferCAL)
button_calc.grid()
########################################################################################################################
#Tab 4 code (What is Modernity?)

#Input Variables
MODquiz1=IntVar()
MODquiz2=IntVar()
MODquiz3=IntVar()
MODquiz4=IntVar()
MODquiz1_b=IntVar()
MODquiz2_b=IntVar()
MODquiz3_b=IntVar()
MODquiz4_b=IntVar()

MODass1=IntVar()
MODass2=IntVar()
MODass3=IntVar()
MODass1_b=IntVar()
MODass2_b=IntVar()
MODass3_b=IntVar()

MODfinal=IntVar()
MODfinal_b=IntVar()

MODpart=IntVar()
MODpart_b=IntVar()

#Line Skipping Variables
empty1=Label(page4, text='                                                                                         ')
empty2=Label(page4, text='                                                                                         ')
empty3=Label(page4, text='                                                                                         ')
empty4=Label(page4, text='                                                                                         ')
empty5=Label(page4, text='                                                                                         ')
empty6=Label(page4, text='                                                                                         ')
empty7=Label(page4, text='                                                                                         ')
empty8=Label(page4, text='                                                                                         ')
empty9=Label(page4, text='                                                                                         ')
empty10=Label(page4, text='                                                                                         ')

empty1.grid(row=2, column=1)

#Input Header Text
header = Label(page4, text='Marks Obtained') #Create Text
header.grid(row=2, column=2) #Place Text onto Window
empty2.grid(row=2, column=3)
header_two=Label(page4, text='Maximum Marks')
header_two.grid(row=2, column=3)

#Text and Fields for Obtained Marks and Maximum Marks (User Input)
Field_one = Label(page4, text='Quiz 01') #Create Text
entry_one = Entry(page4, textvariable=MODquiz1) #Create Textfield
entry_one_b = Entry(page4, textvariable=MODquiz1_b)
Field_two = Label(page4, text='Quiz 02')
entry_two = Entry(page4, textvariable=MODquiz2)
entry_two_b = Entry(page4, textvariable=MODquiz2_b)
Field_three = Label(page4, text='Quiz 03')
entry_three = Entry(page4, textvariable=MODquiz3)
entry_three_b = Entry(page4, textvariable=MODquiz3_b)
Field_four = Label(page4, text='Quiz 04')
entry_four= Entry(page4, textvariable=MODquiz4)
entry_four_b= Entry(page4, textvariable=MODquiz4_b)
Field_five = Label(page4, text='Essay 01')
entry_five = Entry(page4, textvariable=MODass1)
entry_five_b = Entry(page4, textvariable=MODass1_b)
Field_six = Label(page4, text='Essay 02')
entry_six = Entry(page4, textvariable=MODass2)
entry_six_b = Entry(page4, textvariable=MODass2_b)
Field_seven = Label(page4, text='Essay 03')
entry_seven = Entry(page4, textvariable=MODass3)
entry_seven_b = Entry(page4, textvariable=MODass3_b)
Field_eight = Label(page4, text='Final Exam')
entry_eight = Entry(page4, textvariable=MODfinal)
entry_eight_b = Entry(page4, textvariable=MODfinal_b)
Field_nine = Label(page4, text='Class Participation')
entry_nine = Entry(page4, textvariable=MODpart)
entry_nine_b = Entry(page4, textvariable=MODpart_b)

Field_one.grid(row=3, column=1) #Place Text onto window
entry_one.grid(row=3, column=2) #Place Textfield onto window
Field_two.grid(row=4, column=1)
entry_two.grid(row=4, column=2)
Field_three.grid(row=5, column=1)
entry_three.grid(row=5, column=2)
Field_four.grid(row=6, column=1)
entry_four.grid(row=6, column=2)
empty3.grid(row=7)
Field_five.grid(row=8, column=1)
entry_five.grid(row=8, column=2)
Field_six.grid(row=9, column=1)
entry_six.grid(row=9, column=2)
Field_seven.grid(row=10, column=1)
entry_seven.grid(row=10, column=2)
empty4.grid(row=11)
Field_eight.grid(row=12, column=1)
entry_eight.grid(row=12, column=2)
empty5.grid(row=13)
Field_nine.grid(row=14, column=1)
entry_nine.grid(row=14, column=2)

entry_one_b.grid(row=3, column=3)
entry_two_b.grid(row=4, column=3)
entry_three_b.grid(row=5, column=3)
entry_four_b.grid(row=6, column=3)
empty6.grid(row=7)
entry_five_b.grid(row=8, column=3)
entry_six_b.grid(row=9, column=3)
entry_seven_b.grid(row=10, column=3)
empty7.grid(row=11)
entry_eight_b.grid(row=12, column=3)
empty8.grid(row=13)
entry_nine_b.grid(row=14, column=3)

#Button
button_modernity = Button(page4, text='The Moment of Truth', bg='#f56108', fg='white', command=transferMOD)
button_modernity.grid()
########################################################################################################################
#Tab 5 code (Intro to Sustainability)

#Input Variables
Sass1=IntVar()
Sass2=IntVar()
Sass3=IntVar()
Sass1_b=IntVar()
Sass2_b=IntVar()
Sass3_b=IntVar()

Smid=IntVar()
Smid_b=IntVar()

Sfinal=IntVar()
Sfinal_b=IntVar()

Spart=IntVar()
Spart_b=IntVar()

#Line Skipping Variables
empty1=Label(page5, text='                                                                                         ')
empty2=Label(page5, text='                                                                                         ')
empty3=Label(page5, text='                                                                                         ')
empty4=Label(page5, text='                                                                                         ')
empty5=Label(page5, text='                                                                                         ')
empty6=Label(page5, text='                                                                                         ')
empty7=Label(page5, text='                                                                                         ')
empty8=Label(page5, text='                                                                                         ')
empty9=Label(page5, text='                                                                                         ')
empty10=Label(page5, text='                                                                                         ')

empty1.grid(row=2, column=1)

#Input Header Text
header = Label(page5, text='Marks Obtained') #Create Text
header.grid(row=2, column=2) #Place Text onto Window
empty2.grid(row=2, column=3)
header_two=Label(page5, text='Maximum Marks')
header_two.grid(row=2, column=3)

#Text and Fields for Obtained Marks and Maximum Marks (User Input)
Field_one = Label(page5, text='Assignment 01') #Create Text
entry_one = Entry(page5, textvariable=Sass1) #Create Textfield
entry_one_b = Entry(page5, textvariable=Sass1_b)
Field_two = Label(page5, text='Assignment 02')
entry_two = Entry(page5, textvariable=Sass2)
entry_two_b = Entry(page5, textvariable=Sass2_b)
Field_three = Label(page5, text='Assignment 03')
entry_three = Entry(page5, textvariable=Sass3)
entry_three_b = Entry(page5, textvariable=Sass3_b)
Field_four = Label(page5, text='Mid-Term Exam')
entry_four= Entry(page5, textvariable=Smid)
entry_four_b= Entry(page5, textvariable=Smid_b)
Field_five = Label(page5, text='Final Exam')
entry_five = Entry(page5, textvariable=Sfinal)
entry_five_b = Entry(page5, textvariable=Sfinal_b)
Field_six = Label(page5, text='Class Participation')
entry_six = Entry(page5, textvariable=Spart)
entry_six_b = Entry(page5, textvariable=Spart_b)

Field_one.grid(row=3, column=1) #Place Text onto window
entry_one.grid(row=3, column=2) #Place Textfield onto window
Field_two.grid(row=4, column=1)
entry_two.grid(row=4, column=2)
Field_three.grid(row=5, column=1)
entry_three.grid(row=5, column=2)
empty3.grid(row=6)
Field_four.grid(row=7, column=1)
entry_four.grid(row=7, column=2)
Field_five.grid(row=8, column=1)
entry_five.grid(row=8, column=2)
empty4.grid(row=9)
Field_six.grid(row=10, column=1)
entry_six.grid(row=10, column=2)

entry_one_b.grid(row=3, column=3)
entry_two_b.grid(row=4, column=3)
entry_three_b.grid(row=5, column=3)
empty5.grid(row=6, column=1)
entry_four_b.grid(row=7, column=3)
entry_five_b.grid(row=8, column=3)
empty6.grid(row=9)
entry_six_b.grid(row=10, column=3)

#Button
button_sustainability = Button(page5, text='The Moment of Truth', bg='#f56108', fg='white', command=transferS)
button_sustainability.grid()
########################################################################################################################
window2.mainloop()